# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13d25f7430e133f5488e7ce395e140bacd162b49c64c63658d9642159befe5fae59955afb083190579a2d64fa32697a43e09c947683dba424cbaa29d569bcf14

test:
  secret_key_base: e01d0d56779e08382518a6d1d6f55459ff776c69f99b3c3f4ea642f0afa1d60ca20355a780dc07aad3689f3f0c7c3b5b3918f1e6b654a562dcc429899e9b55eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
